name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: "Production"

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set env variable CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Verify Git installation
        run: git --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          ADSB_TOKEN: 
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        run: |
          echo "ADSB_TOKEN=${{ secrets.ADSB_TOKEN }}" >> $ADSB_TOKEN
          echo "MAPBOX_TOKEN: $MAPBOX_TOKEN"
